import type { Metadata } from "next";
import Navbar from "../components/ui/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerece",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
      <body className={inter.className}>
        {/* Include shared UI here e.g. a header or sidebar */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
